{% set name = "GFAffix" %}
{% set version = "0.1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/marschall-lab/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: a1f97becfeb257c06d6c71dd42f6a47a91880e8c3bbbd66422eac5ee6bd38c46 

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - rust >=1.55

test:
  commands:
    - gfaffix --help

about:
  home: https://github.com/marschall-lab/{{ name }}
  license: MIT
  license_file: LICENSE.md
  summary: GFAffix identifies and collapses walk-preserving shared affixes in variation graphs 

extra:
  recipe-maintainers:
    - danydoerr
